apiVersion: apps/v1
kind: Deployment
metadata:
  name: webcomics-deployment
  labels:
    app: webcomics
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: webcomics
  template:
    metadata:
      name: webcomics
      labels:
        app: webcomics
    spec:
      imagePullSecrets:
        - name: registry.internal.aleemhaji.com
      containers:
        - name: webcomics
          image: registry.internal.aleemhaji.com/webcomics:latest
          ports:
            - containerPort: 80
          env:
            - name: PORT
              value: "80"
            - name: DATABASE
              valueFrom:
                secretKeyRef:
                  name: webcomics-secrets
                  key: database
---
apiVersion: v1
kind: Service
metadata:
  name: webcomics
  labels:
    app: webcomics
spec:
  ports:
    - port: 80
      protocol: TCP
  type: NodePort
  selector:
    app: webcomics
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: webcomic-scraper-schedule
spec:
  schedule: "0 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: webcomic-scraper-schedule
              image: curlimages/curl:7.72.0
              command:
                - sh
                - -c
                - curl -X POST http://${WEBCOMICS_HOST}/tasks/fetch/comic 
              env:
                - name: WEBCOMICS_HOST
                  value: webcomics
