apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-pv
  labels:
    identifier: registry
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=3
  nfs:
    path: /kubernetes-test/registry
    server: 192.168.1.42
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  selector:
    matchLabels:
      identifier: registry
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: registry-deployment
  labels:
    app: registry
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
        - name: registry
          image: registry:2
          ports:
            - containerPort: 80
          volumeMounts:
            - name: registry-persistent-storage
              mountPath: /var/lib/registry
            - name: htpasswd-secrets
              mountPath: /auth
          env:
            - name: REGISTRY_HTTP_ADDR
              value: 0.0.0.0:80
            - name: REGISTRY_AUTH
              value: "htpasswd"
            - name: REGISTRY_AUTH_HTPASSWD_REALM
              value: "registry.internal.aleemhaji.com"
            - name: REGISTRY_AUTH_HTPASSWD_PATH
              value: /auth/htpasswd
      volumes:
        - name: registry-persistent-storage
          persistentVolumeClaim:
            claimName: registry-pv-claim
        - name: htpasswd-secrets
          projected:
            sources:
              - secret:
                  name: registry-htpasswd-secret
---
apiVersion: v1
kind: Service
metadata:
  name: registry
  labels:
    app: registry
spec:
  ports:
    - port: 80
      # nodePort: 5000
      protocol: TCP
  type: LoadBalancer
  loadBalancerIP: 192.168.2.222
  selector:
    app: registry
