global: 
  resolve_timeout: 5m
receivers: 
  - name: slack
    webhook_configs:
      - url: http://slack-bot/message
route: 
  group_by: 
    - job
  group_interval: 5m
  group_wait: 30s
  receiver: slack
  repeat_interval: 12h
  routes: 
    - match: 
        alertname: Watchdog
      receiver: slack
