version: '3'
services:
  sharelatex:
    volumes:
      - '/var/lib/sharelatex:/var/lib/sharelatex'
  mongodb:
    volumes:
      - '/var/lib/mongodb/data:/data/db'
  mysql:
    volumes:
      - '/var/lib/mysql:/var/lib/data'
      - '/var/lib/backups/mysql:/var/lib/backup'
  transmission-oss:
    volumes:
      - '/var/lib/transmission-oss/downloads:/var/lib/transmission-daemon/downloads'
      - '/var/lib/transmission-oss/watch:/var/lib/transmission-daemon/watch'
      - '/var/lib/transmission-oss/info/resume:/var/lib/transmission-daemon/info/resume'
      - '/var/lib/transmission-oss/info/torrents:/var/lib/transmission-daemon/info/torrents'
  util:
    volumes:
      - '/var/lib/backups:/var/lib/backups'
      - '/var/lib/git:/var/lib/git'
    ports:
      - '22:22'
  resilio-server:
    volumes:
      - /var/lib/.sync:/.sync
      - /var/lib/backups:/var/lib/resilio-folders
  plex:
    volumes:
      - /var/lib/plex:/config
