version: '3'
services:
  sharelatex:
    volumes:
      - 'sharelatex-data:/var/lib/sharelatex'
  mongodb:
    volumes:
      - 'mongodb-data:/db/data'
  mysql:
    volumes:
      - 'mysql-data:/var/lib/data'
  util:
    ports:
      - '2000:22'
  plex:
    volumes:
      - plex-config:/config

volumes:
  sharelatex-data:
    external: true
  mongodb-data:
    external: true
  mysql-data:
    external: true
  plex-config:
    external: true
