version: '3'
services:
  sharelatex:
    volumes:
      - 'sharelatex-data:/var/lib/sharelatex'
  mongodb:
    volumes:
      - 'mongodb-data:/db/data'
      - 'D:/DockerBackups/mongodb:/var/lib/backup'
  mysql:
    volumes:
      - 'mysql-data:/var/lib/data'
      - 'D:/DockerBackups/mysql:/var/lib/backup'
  util:
    ports:
      - '22:22'
  plex:
    volumes:
      - plex-config:/config

volumes:
  sharelatex-data:
    external: true
  mongodb-data:
    external: true
  mysql-data:
    external: true
  plex-config:
    external: true
