# This compose file consists of all the base level configurations that will
#   need to exist on any of the containers regardless of the platform they're
#   being run on.
# The three other compose files:
#   - .cygwin.
#   - .darwin.
#   - .linux.
#   are to provide the platform specific configurations to make sure that
#   discrepancies between testing and running environments can be taken into
#   account.
version: '3'
services:
  pi-hole:
    build: pi-hole
    env_file: pi-hole/compose.env
    hostname: pi-hole
    ports:
      - 8080:80
      - 53:53/tcp
      - 53:53/udp
    dns: 127.0.0.1

  sharelatex:
    build: sharelatex
    hostname: sharelatex
    ports:
      - 8081:80
    links:
      - mongo
      - redis
    depends_on:
      - mongo
      - redis

  plex:
    image: plexinc/pms-docker
    environment:
      - ALLOWED_NETWORKS=192.168.1.0/24
    hostname: plex
    env_file: plex/compose.env
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
