version: '3'
services:
  pi-hole:
    build: pi-hole
    env_file: pi-hole/compose.env
    ports:
      - 80:80
      - 53:53/tcp
      - 53:53/udp
    dns: 127.0.0.1

  redis:
    build: redis
    ports:
      - 6379:6379

  mongodb:
    build: mongodb
    ports: 
      - 27017:27017

  sharelatex:
    build: sharelatex
    ports:
      - 8081:80
    depends_on:
      - mongodb
      - redis

  mysql:
    build: mysql
    env_file: mysql/compose.env
    ports:
      - 3306:3306

  firefly-iii:
    build: firefly-iii
    env_file: firefly-iii/compose.env
    ports:
      - 8082:80
    depends_on:
      - mysql
