# This compose file consists of all the base level configurations that will
#   need to exist on any of the containers regardless of the platform they're
#   being run on.
# The three other compose files:
#   - .cygwin.
#   - .darwin.
#   - .linux.
#   are to provide the platform specific configurations to make sure that
#   discrepancies between testing and running environments can be taken into
#   account.
version: '3'
services:
  sharelatex:
    build: sharelatex
    hostname: sharelatex
    ports:
      - 8081:80
    links:
      - mongo
      - redis
    depends_on:
      - mongo
      - redis
