version: '3'
services:
  sharelatex:
    volumes:
      - '/var/lib/sharelatex:/var/lib/sharelatex'
  mongodb:
    volumes:
      - '/var/lib/mongodb/data:/data/db'
  mysql:
    volumes:
      - '/var/lib/mysql:/var/lib/data'
  util:
    ports:
      - '22:22'
  plex:
    volumes:
      - /var/lib/plex:/config
