version: '3'
services:
  sharelatex:
    volumes:
      - '/var/lib/sharelatex:/var/lib/sharelatex'
  mongodb:
    volumes:
      - /var/lib/mongodb/data:/db/data
  mysql:
    volumes:
      - '/var/lib/mysql:/var/lib/data'
