masters:
  - root@192.168.200.10
nodes:
  - ubuntu@192.168.200.10
  - ubuntu@192.168.200.11
loglevel: trace
pod_network_cidr: 10.244.0.0/16
resources:
  - name: flannel
    file: https://raw.githubusercontent.com/coreos/flannel/v0.12.0/Documentation/kube-flannel.yml
    tags: [network]
  - name: flannel-rbac
    file: https://raw.githubusercontent.com/coreos/flannel/v0.12.0/Documentation/k8s-manifests/kube-flannel-rbac.yml
    tags: [network]
  - name: dashboard
    file: https://raw.githubusercontent.com/kubernetes/dashboard/v1.10.1/src/deploy/recommended/kubernetes-dashboard.yaml
    tags: [apps, dashboard]
  - name: metrics-server
    file: metrics-server.yaml
  - name: grafana
    file: grafana/grafana.yaml
  - name: personal-service-account
    inline: |
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: aleem
        namespace: kube-system
      ---
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: aleem
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: cluster-admin
      subjects:
      - kind: ServiceAccount
        name: aleem
        namespace: kube-system
    tags: [users]
  - name: load-balancer-namespace
    file: https://raw.githubusercontent.com/metallb/metallb/v0.8.3/manifests/namespace.yaml
    tags: [network, load-balancer]
  - name: load-balancer
    file: https://raw.githubusercontent.com/metallb/metallb/v0.8.3/manifests/metallb.yaml
    tags: [network, load-balancer]
  - name: load-balancer-config
    inline: |
      apiVersion: v1
      kind: ConfigMap
      metadata:
        namespace: metallb-system
        name: config
      data:
        config: |
          address-pools:
          - name: default
            protocol: layer2
            addresses:
            - 192.168.200.32-192.168.200.224
    tags: [network, load-balancer]
  - name: ingress-controller-configs
    inline: |
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: tcp-services
      data:
        3306: "default/mysql:3306"
        5432: "default/postgres:5432"
        6379: "default/redis:6379"
        9443: "default/openvpnas-tcp:9443"
        27017: "default/mongodb:27017"
        51413: "default/osstransmission:51413"
      ---
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: udp-services
      data:
        1194: "default/openvpnas-udp:1194"
        34197: "default/factorio:34197"
      ---
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: ingress-nginx-controller
        namespace: ingress-nginx
      data:
        http-redirect-code: "302"
    tags: [network, ingress]
  - name: ingress-controller
    file: nginx-ingress-plus-tcp-udp-proxy.yaml
    tags: [network, ingress]
  - name: ingress-controller-service
    inline: |
      apiVersion: v1
      kind: Service
      metadata:
        name: nginx-ingress-tcp
        labels:
          app: nginx-ingress
        namespace: ingress-nginx
        annotations:
          metallb.universe.tf/allow-shared-ip: ingress
      spec:
        ports:
        - port: 53
          name: dns
          protocol: TCP
        - port: 80
          name: http
          protocol: TCP
        - port: 443
          name: https
          protocol: TCP
        - port: 3306
          name: mysql
          protocol: TCP
        - port: 5432
          name: postgres
          protocol: TCP
        - port: 6379
          name: redis
          protocol: TCP
        - port: 9443
          name: openvpn
          protocol: TCP
        - port: 27017
          name: mongodb
          protocol: TCP
        - port: 51413
          name: osstransmission
          protocol: TCP
        type: LoadBalancer
        loadBalancerIP: 192.168.200.128
        selector:
          app.kubernetes.io/name: ingress-nginx
      ---
      apiVersion: v1
      kind: Service
      metadata:
        name: nginx-ingress-udp
        labels:
          app: nginx-ingress
        namespace: ingress-nginx
        annotations:
          metallb.universe.tf/allow-shared-ip: ingress
      spec:
        ports:
        - port: 53
          name: dns
          protocol: UDP
        - port: 1194
          name: openvpn
          protocol: UDP
        - port: 34197
          name: factorio
          protocol: UDP
        type: LoadBalancer
        loadBalancerIP: 192.168.200.128
        selector:
          app.kubernetes.io/name: ingress-nginx
    tags: [network, ingress]
  - name: kubernetes-dashboard-ingress
    inline: |
      apiVersion: extensions/v1beta1
      kind: Ingress
      metadata:
        namespace: kube-system
        name: dashboard-ingress-redirect
        annotations:
          kubernetes.io/ingress.class: "nginx"
          nginx.ingress.kubernetes.io/temporal-redirect: https://dashboard.internal.aleemhaji.com
      spec:
        rules:
          - host: dashboard
          - host: dashboard.home
      ---
      apiVersion: extensions/v1beta1
      kind: Ingress
      metadata:
        namespace: kube-system
        name: dashboard-ingress
        annotations:
          kubernetes.io/ingress.class: "nginx"
          nginx.ingress.kubernetes.io/backend-protocol: "https"
      spec:
        tls:
          - hosts:
              - dashboard.internal.aleemhaji.com
            secretName: internal-certificate-files
        rules:
          - host: dashboard.internal.aleemhaji.com
            http:
              paths:
                - path: /
                  backend:
                    serviceName: kubernetes-dashboard
                    servicePort: 443
    tags: [apps, dashboard]
  - name: docker-registry-secrets
    inline: |
      apiVersion: v1
      data:
        .dockerconfigjson: ${DOCKER_CONFIG_JSON_FILE_CONTENTS_BASE64}
      kind: Secret
      metadata:
        name: ${DOCKER_REGISTRY_HOSTNAME}
      type: kubernetes.io/dockerconfigjson
      ---
      apiVersion: v1
      data:
        htpasswd: ${DOCKER_HTPASSWD_FILE_CONTENTS_BASE64}
      kind: Secret
      metadata:
        name: ${DOCKER_REGISTRY_HOSTNAME}-htpasswd
    parameters:
      - DOCKER_REGISTRY_HOSTNAME
      - DOCKER_HTPASSWD_FILE_CONTENTS_BASE64
      - DOCKER_CONFIG_JSON_FILE_CONTENTS_BASE64
    tags: [apps, registry]
  - name: docker-registry
    file: registry/registry.yaml
    tags: [apps, registry]
  - name: browser
    file: browser/browser.yaml
    tags: [apps, browser]
  - name: heimdall
    file: heimdall/heimdall.yaml
    tags: [apps, heimdall]
  - name: trilium
    file: trilium/trilium.yaml
    tags: [apps, trilium]
  - name: slackbot-image
    build:
      path: slackbot
      tag: registry.internal.aleemhaji.com/slackbot:latest
    tags: [apps, slackbot]
  - name: slackbot-config
    inline: |
      apiVersion: v1
      data:
        alerting_channel: ${SLACK_BOT_ALERTING_CHANNEL}
        default_channel: ${SLACK_BOT_DEFAULT_CHANNEL}
      kind: ConfigMap
      metadata:
        name: slack-bot-config
      ---
      apiVersion: v1
      data:
        api_key: ${SLACK_BOT_API_KEY_BASE64}
      kind: Secret
      metadata:
        name: slack-bot-secrets
    parameters:
      - SLACK_BOT_ALERTING_CHANNEL
      - SLACK_BOT_DEFAULT_CHANNEL
      - SLACK_BOT_API_KEY_BASE64
    tags: [apps, slackbot]
  - name: slackbot
    file: slackbot/slackbot.yaml
    tags: [apps, slackbot]
  - name: firefly-config
    inline: |
      apiVersion: v1
      data:
        mysql_user: ${FIREFLY_MYSQL_USER}
        mysql_database: ${FIREFLY_MYSQL_DATABASE}
      kind: ConfigMap
      metadata:
        name: firefly-config
      ---
      apiVersion: v1
      data:
        mysql_password: ${FIREFLY_MYSQL_PASSWORD_BASE64}
        app_key: ${FIREFLY_APP_KEY_BASE64}
      kind: Secret
      metadata:
        name: firefly-secrets
    parameters:
      - FIREFLY_MYSQL_USER
      - FIREFLY_MYSQL_DATABASE
      - FIREFLY_MYSQL_PASSWORD_BASE64
      - FIREFLY_APP_KEY_BASE64
    tags: [apps, firefly]
  - name: firefly-init-job-create
    file: firefly/firefly-init.yaml
    tags: [apps, firefly]
  - name: firefly-init-job
    job: firefly-mysql-init
    tags: [apps, firefly]
  - name: firefly
    file: firefly/firefly.yaml
    tags: [apps, firefly]
  - name: guacamole-config
    inline: |
      apiVersion: v1
      data:
        mysql_user: ${GUACAMOLE_MYSQL_USER}
        mysql_database: ${GUACAMOLE_MYSQL_DATABASE}
      kind: ConfigMap
      metadata:
        name: guacamole-config
      ---
      apiVersion: v1
      data:
        mysql_password: ${GUACAMOLE_MYSQL_PASSWORD_BASE64}
      kind: Secret
      metadata:
        name: guacamole-secrets
    parameters:
      - GUACAMOLE_MYSQL_USER
      - GUACAMOLE_MYSQL_DATABASE
      - GUACAMOLE_MYSQL_PASSWORD_BASE64
    tags: [apps, guacamole]
  - name: guacamole-init-job-create
    file: guacamole/guacamole-init.yaml
    tags: [apps, guacamole]
  - name: guacamole-init-job
    job: guacamole-mysql-init
    tags: [apps, guacamole]
  - name: guacamole
    file: guacamole/guacamole.yaml
    tags: [apps, guacamole]
  - name: resilio-sync-config
    inline: |
      apiVersion: v1
      data:
        username: ${RESILIO_SERVER_USERNAME}
      kind: ConfigMap
      metadata:
        name: resilio-sync-config
      ---
      apiVersion: v1
      data:
        password: ${RESILIO_SERVER_PASSWORD_BASE64}
      kind: Secret
      metadata:
        name: resilio-sync-secrets
    parameters:
      - RESILIO_SERVER_USERNAME
      - RESILIO_SERVER_PASSWORD_BASE64
    tags: [apps, resilio-sync]
  - name: resilio-sync-image
    build:
      path: resilio-sync
      tag: registry.internal.aleemhaji.com/resilio:latest
    tags: [apps, resilio-sync]
  - name: resilio-sync
    file: resilio-sync/resilio-sync.yaml
    tags: [apps, resilio-sync]
  - name: node-red-config
    inline: |
      apiVersion: v1
      data:
        mysql_user: ${NODE_RED_MYSQL_USER}
        mysql_database: ${NODE_RED_MYSQL_DATABASE}
      kind: ConfigMap
      metadata:
        name: node-red-config
      ---
      apiVersion: v1
      data:
        mysql_password: ${NODE_RED_MYSQL_PASSWORD_BASE64}
      kind: Secret
      metadata:
        name: node-red-secrets
    parameters:
      - NODE_RED_MYSQL_USER
      - NODE_RED_MYSQL_DATABASE
      - NODE_RED_MYSQL_PASSWORD_BASE64
    tags: [apps, node-red]
  - name: node-red-image
    build:
      path: node-red
      tag: registry.internal.aleemhaji.com/node-red:latest
    tags: [apps, node-red]
  - name: node-red-init-job-create
    file: node-red/node-red-init.yaml
    tags: [apps, node-red]
  - name: node-red-init-job
    job: node-red-mysql-init
    tags: [apps, node-red]
  - name: node-red
    file: node-red/node-red.yaml
    tags: [apps, node-red]
  - name: redis
    file: redis/redis.yaml
    tags: [apps, redis]
  - name: postgres-config
    inline: |
      apiVersion: v1
      data:
        root_password: ${POSTGRES_ROOT_PASSWORD_BASE64}
      kind: Secret
      metadata:
        name: postgres-secrets
    parameters:
      - POSTGRES_ROOT_PASSWORD_BASE64
    tags: [apps, postgres]
  - name: postgres-block-storage
    file: postgres/postgres-block-storage.yaml
    tags: [apps, postgres]
  - name: postgres
    file: postgres/postgres.yaml
    tags: [apps, postgres]
  - name: mysql-block-storage
    file: mysql/mysql-block-storage.yaml
    tags: [apps, mysql]
  - name: mysql-config
    inline: |
      apiVersion: v1
      data:
        root_password: ${MYSQL_ROOT_PASSWORD_BASE64}
      kind: Secret
      metadata:
        name: mysql-secrets
    parameters:
      - MYSQL_ROOT_PASSWORD_BASE64
    tags: [apps, mysql]
  - name: mysql-backup
    inline: |
      apiVersion: v1
      data:
        mysql-backup.sh: |
          #!/bin/sh
          set -e

          if [ -z "${MYSQL_HOST}" ]; then
              echo >&2 "Must provide MYSQL_HOST to backup"
              exit 1
          fi

          if [ -z "${MYSQL_PWD}" ]; then
              echo >&2 "Must provide MYSQL_PWD for root@${MYSQL_HOST}"
              exit 2
          fi

          mysql -h ${MYSQL_HOST} -u root -s -N -e "show databases;" | while read database; do
              if [ "$database" = "information_schema" ] || [ "$database" = "mysql" ] || [ "$database" = "sys" ] || [ "$database" = "performance_schema" ]; then
                  echo >&2 "Skipping database $database"
                  continue
              fi

              echo >&2 "Backing up database: $database"
              mkdir -p "/var/lib/backups/$database"
              mysql -h ${MYSQL_HOST} -u root -s -N -c "$database" -e "show tables;" | while read table; do
                  mysqldump -h ${MYSQL_HOST} -u root --skip-dump-date "$database" "$table" > "/var/lib/backups/$database/$table.sql"
              done || exit 1
          done || exit 1
      kind: ConfigMap
      metadata:
        name: mysql-backup
    tags: [apps, mysql]
  - name: mysql
    file: mysql/mysql.yaml
    tags: [apps, mysql]
  - name: mongodb-block-storage
    file: mongodb/mongodb-block-storage.yaml
    tags: [apps, mongodb]
  - name: mongodb-backup
    inline: |
      apiVersion: v1
      data:
        mongodb-backup.sh: |
          #!/bin/sh
          set -e

          if [ -z "${MONGODB_HOST}" ]; then
              echo >&2 "Must provide MONGODB_HOST to backup"
              exit 1
          fi

          mongo --host ${MONGODB_HOST} --quiet --eval 'db.getMongo().getDBNames().join("\n");' | while read database; do
              set -e

              if [ "$database" = "admin" ] || [ "$database" = "local" ] || [ "$database" = "config" ] || [ "$database" = "unifi_stat" ] || [ "$database" = "dev" ]; then
                  echo >&2 "Skipping database $database"
                  continue
              fi

              echo >&2 "Backing up database: $database"
              if [ "$database" = "remind-me-bot" ] || [ "$database" = "blobstore" ]; then
                  echo >&2 "Skipping logs collection"
                  mongodump --host ${MONGODB_HOST} --db "$database" --excludeCollection=logs -o "/var/lib/backups/$database"
              else
                  mongodump --host ${MONGODB_HOST} --db "$database" -o "/var/lib/backups/$database"
              fi
          done
      kind: ConfigMap
      metadata:
        name: mongodb-backup
    tags: [apps, mongodb]
  - name: mongodb
    file: mongodb/mongodb.yaml
    tags: [apps, mongodb]
  - name: openvpnas-config
    inline: |
      apiVersion: v1
      data:
        username: ${OPENVPN_PRIMARY_USERNAME}
        hostname: ${OPENVPN_AS_HOSTNAME}
      kind: ConfigMap
      metadata:
        name: openvpn-config
      ---
      apiVersion: v1
      data:
        password: ${OPENVPN_PRIMARY_PASSWORD_BASE64}
      kind: Secret
      metadata:
        name: openvpn-secrets
    parameters:
      - OPENVPN_PRIMARY_USERNAME
      - OPENVPN_AS_HOSTNAME
      - OPENVPN_PRIMARY_PASSWORD_BASE64
    tags: [apps, openvpn]
  - name: openvpnas
    file: openvpnas/openvpnas.yaml
    tags: [apps, openvpn]
  - name: openvpnas-init
    exec:
      selector: deploy/openvpnas-deployment
      # Container is a Linuxserver.io one, so it's going to be slow af.
      timeout: 3m
      command:
        - bash
        - -xec
        - |
          find /scripts -type f | sort | while read line; do
            sh $line;
          done
    tags: [apps, openvpn]
  - name: dns-update-config
    inline: |
      apiVersion: v1
      data:
        value: ${NAMESILO_API_KEY_BASE64}
      kind: Secret
      metadata:
        name: namesilo-api-key
    parameters:
      - NAMESILO_API_KEY_BASE64
    tags: [crons, dns]
  - name: dns-update-cron
    file: crons/dns-cron.yaml
    tags: [crons, dns]
  - name: remindmebot-config
    inline: |
      apiVersion: v1
      data:
        bot_username: ${REMINDMEBOT_USERNAME}
      kind: ConfigMap
      metadata:
        name: remindmebot-config
      ---
      apiVersion: v1
      data:
        bot_api_key: ${REMINDMEBOT_API_KEY_BASE64}
        database: ${REMINDMEBOT_DATABASE_BASE64}
      kind: Secret
      metadata:
        name: remindmebot-secrets
    parameters:
      - REMINDMEBOT_USERNAME
      - REMINDMEBOT_API_KEY_BASE64
      - REMINDMEBOT_DATABASE_BASE64
    tags: [apps, remindmebot]
  - name: remindmebot-init-job-start
    file: remindmebot/remindmebot-init.yaml
    tags: [apps, remindmebot]
  - name: remindmebot-init-job
    job: remindmebot-init
    tags: [apps, remindmebot]
  - name: remindmebot
    file: remindmebot/remindmebot.yaml
    tags: [apps, remindmebot]
  - name: tedbot-config
    inline: |
      apiVersion: v1
      data:
        slack_webhook_url: ${SLACK_TEDBOT_APP_WEBHOOK_BASE64}
      kind: Secret
      metadata:
        name: tedbot-secrets
    parameters:
      - SLACK_TEDBOT_APP_WEBHOOK_BASE64
    tags: [crons, tedbot]
  - name: tedbot
    file: tedbot/tedbot.yaml
    tags: [crons, tedbot]
  - name: factorio-image
    build:
      path: factorio
      tag: registry.internal.aleemhaji.com/factorio:latest
    tags: [apps, factorio]
  - name: factorio
    file: factorio/factorio.yaml
    tags: [apps, factorio]
  - name: blobstore-config
    inline: |
      apiVersion: v1
      data:
        database: ${BLOBSTORE_DATABASE_BASE64}
      kind: Secret
      metadata:
        name: blobstore-secrets
    parameters:
      - BLOBSTORE_DATABASE_BASE64
    tags: [apps, blobstore]
  - name: blobstore
    file: blobstore/blobstore.yaml
    tags: [apps, blobstore]
  - name: webcomics-config
    inline: |
      apiVersion: v1
      data:
        database: ${WEBCOMICS_DATABASE_BASE64}
      kind: Secret
      metadata:
        name: webcomics-secrets
    parameters:
      - WEBCOMICS_DATABASE_BASE64
    tags: [apps, webcomics]
  - name: webcomics
    file: webcomics/webcomics.yaml
    tags: [apps, webcomics]
  - name: transmission-image
    build:
      path: transmission
      tag: registry.internal.aleemhaji.com/transmission:latest
    tags: [apps, transmission]
  - name: osstransmission
    file: transmission/transmission.yaml
    tags: [apps, transmission]
  - name: certbot-update-kube-system
    file: certbot/certbot-generic-cron.yaml
    parameters:
      - KUBERNETES_NAMESPACE=kube-system
      - INCLUDE_EXTERNAL_CERTS=false
    tags: [crons, certbot]
  - name: certbot-update-monitoring
    file: certbot/certbot-generic-cron.yaml
    parameters:
      - KUBERNETES_NAMESPACE=monitoring
      - INCLUDE_EXTERNAL_CERTS=false
    tags: [crons, certbot]
  - name: certbot-update-default
    file: certbot/certbot-generic-cron.yaml
    parameters:
      - KUBERNETES_NAMESPACE=default
      - INCLUDE_EXTERNAL_CERTS=true
    tags: [crons, certbot]
  - name: certbot-cron
    file: certbot/certbot.yaml
    tags: [crons, certbot]
jobs:
  - name: mysql-restore
    file: mysql/tasks/mysql-restore.yaml
    parameters:
      - MYSQL_DATABASE_NAME
  - name: mysql-drop
    file: mysql/tasks/mysql-drop.yaml
    parameters:
      - MYSQL_DATABASE_NAME
  - name: mongodb-restore
    file: mongodb/tasks/mongodb-restore.yaml
    parameters:
      - MONGODB_DATABASE_NAME
