apiVersion: v1
kind: ServiceAccount
metadata:
  name: aleem
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: certbot
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: certbot
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aleem
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: aleem
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: certbot-role
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["secrets"]
  verbs: ["get", "list", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: certbot-manage-secrets
subjects:
- kind: ServiceAccount
  name: certbot
roleRef:
  kind: Role
  name: certbot-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: certbot-role
  namespace: kube-system
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["secrets"]
  verbs: ["get", "list", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: certbot-manage-secrets
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: certbot
  namespace: kube-system
roleRef:
  kind: Role
  name: certbot-role
  apiGroup: rbac.authorization.k8s.io
