apiVersion: v1
kind: PersistentVolume
metadata:
  name: drone-pv
  labels:
    identifier: drone
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=3
  nfs:
    path: /kubernetes-test/drone
    server: 192.168.1.42
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drone-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      identifier: drone
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone-deployment
  labels:
    app: drone
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: drone
  template:
    metadata:
      labels:
        app: drone
    spec:
      containers:
        - name: drone
          image: drone/drone:1.2.3
          env:
            - name: DRONE_GITEA_SERVER
              value: https://gitea.internal.aleemhaji.com
            - name: DRONE_SERVER_HOST
              value: drone.internal.aleemhaji.com
            - name: DRONE_SERVER_PROTO
              value: https
          ports:
            - containerPort: 80
          volumeMounts:
            - name: drone-persistent-storage
              mountPath: /data
            - name: docker-sock
              mountPath: /var/run/docker.sock
      volumes:
        - name: drone-persistent-storage
          persistentVolumeClaim:
            claimName: drone-pv-claim
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
---
apiVersion: v1
kind: Service
metadata:
  name: drone
  labels:
    app: drone
spec:
  ports:
    - port: 80
      protocol: TCP
  type: LoadBalancer
  loadBalancerIP:
  selector:
    app: drone
