apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: slackbot-deployment
  labels:
    app: slackbot
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: slackbot
  template:
    metadata:
      labels:
        app: slackbot
    spec:
      imagePullSecrets:
        - name: registry.internal.aleemhaji.com
      containers:
        - name: slackbot
          image: registry.internal.aleemhaji.com/slackbot:latest
          ports:
            - containerPort: 80
          env:
            - name: DEFAULT_CHANNEL
              valueFrom:
                configMapKeyRef:
                  name: slack-bot-config
                  key: default_channel
            - name: SLACK_API_KEY
              valueFrom:
                secretKeyRef:
                  name: slack-bot-secrets
                  key: api_key
---
apiVersion: v1
kind: Service
metadata:
  name: slackbot
  labels:
    app: slackbot
spec:
  ports:
    - port: 80
      protocol: TCP
  type: LoadBalancer
  loadBalancerIP:
  selector:
    app: slackbot
