apiVersion: apps/v1
kind: Deployment
metadata:
  name: slackbot-deployment
  labels:
    app: slackbot
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: slackbot
  template:
    metadata:
      labels:
        app: slackbot
    spec:
      imagePullSecrets:
        - name: registry.internal.aleemhaji.com
      containers:
        - name: slackbot
          image: registry.internal.aleemhaji.com/slackbot:latest
          ports:
            - containerPort: 80
          env:
            - name: DEFAULT_CHANNEL
              valueFrom:
                configMapKeyRef:
                  name: slack-bot-config
                  key: default_channel
            - name: SLACK_API_KEY
              valueFrom:
                secretKeyRef:
                  name: slack-bot-secrets
                  key: api_key
---
apiVersion: v1
kind: Service
metadata:
  name: slackbot
  labels:
    app: slackbot
spec:
  ports:
    - port: 80
      protocol: TCP
  type: LoadBalancer
  loadBalancerIP:
  selector:
    app: slackbot
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: slackbot-ingress-redirect
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/temporal-redirect: https://slackbot.internal.aleemhaji.com
spec:
  rules:
    - host: slackbot
    - host: slackbot.home
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: slackbot-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
        - slackbot.internal.aleemhaji.com
      secretName: internal-certificate-files
  rules:
    - host: slackbot.internal.aleemhaji.com
      http:
        paths:
          - path: /
            backend:
              serviceName: slackbot
              servicePort: 80
