apiVersion: v1
kind: Service
metadata:
  name: certbot
  labels:
    app: certbot
spec:
  ports:
    - port: 80
      protocol: TCP
  type: LoadBalancer
  loadBalancerIP:
  selector:
    app: certbot
---
# EFF recommends running `certbot renew` a couple times per day.
# Kubernetes doesn't make this kind of pattern very easy.
# An externally accessible endpoint is needed, and it needs access to the
#   certificates volume.
# Run `certbot renew` in an already running certbot pod occasionally.
# This may or may not work depending on how the persistent volume claim works.
# Jobs run successfully, but once renewal time comes up, they may fail.
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: certbot
spec:
  schedule: "32 4,16 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: certbot
        spec:
          restartPolicy: OnFailure
          serviceAccountName: certbot
          imagePullSecrets:
            - name: registry.internal.aleemhaji.com
          containers:
            - name: certbot-renew
              image: certbot/certbot
              command:
                - sh
                - -c
                - -x
                - |
                  certbot renew --no-random-sleep-on-renew --standalone --preferred-challenges http
                  certbot renew --no-random-sleep-on-renew --manual-auth-hook /scripts/dns-renew.sh || true
                  set +x
                  sh /scripts/update-secrets-default.sh
              volumeMounts:
                - name: certbot-storage
                  mountPath: /etc/letsencrypt
                - name: certbot-scripts
                  mountPath: /scripts
              env:
                - name: NAMESILO_API_KEY 
                  valueFrom:
                    secretKeyRef:
                      name: namesilo-api-key
                      key: value
              ports:
                - containerPort: 80
          volumes:
            - name: certbot-storage
              nfs:
                server: 192.168.1.42
                path: /kubernetes-test/certs/letsencrypt
            - name: certbot-scripts
              configMap:
                name: certbot-scripts
                defaultMode: 0777
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: certbot-copy-to-kube-system
  namespace: kube-system
spec:
  schedule: "0 0 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: certbot-copy-to-kube-system
        spec:
          restartPolicy: OnFailure
          serviceAccountName: certbot
          imagePullSecrets:
            - name: registry.internal.aleemhaji.com
          containers:
            - name: certbot-copy-to-kube-system
              image: certbot/certbot
              command:
                - sh
                - /scripts/update-secrets-kube-system.sh
              volumeMounts:
                - name: certbot-storage
                  mountPath: /etc/letsencrypt
                - name: certbot-scripts
                  mountPath: /scripts
          volumes:
            - name: certbot-storage
              nfs:
                server: 192.168.96.4
                path: /mnt/main/apps/certificates
            - name: certbot-scripts
              configMap:
                name: certbot-scripts
                defaultMode: 0777
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: certbot-copy-to-monitoring
  namespace: monitoring
spec:
  schedule: "0 0 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: certbot-copy-to-monitoring
        spec:
          restartPolicy: OnFailure
          serviceAccountName: certbot
          imagePullSecrets:
            - name: registry.internal.aleemhaji.com
          containers:
            - name: certbot-copy-to-monitoring
              image: certbot/certbot
              command:
                - sh
                - /scripts/update-secrets-monitoring.sh
              volumeMounts:
                - name: certbot-storage
                  mountPath: /etc/letsencrypt
                - name: certbot-scripts
                  mountPath: /scripts
          volumes:
            - name: certbot-storage
              nfs:
                server: 192.168.96.4
                path: /mnt/main/apps/certificates
            - name: certbot-scripts
              configMap:
                name: certbot-scripts
                defaultMode: 0777
