apiVersion: v1
kind: PersistentVolume
metadata:
  name: certificates-pv
  labels:
    identifier: certificates
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=3
  nfs:
    path: /kubernetes-test/certs/letsencrypt
    server: 192.168.1.42
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: certificates-pv-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      identifier: certificates
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: certbot-deployment
  labels:
    app: certbot
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: certbot
  template:
    metadata:
      labels:
        app: certbot
    spec:
      containers:
        - name: certbot
          image: certbot/certbot
          ports:
            - containerPort: 80
          command: ["/bin/sh"]
          stdin: true 
          tty: true
          volumeMounts:
          - name: certbot-storage
            mountPath: /etc/letsencrypt
      volumes:
        - name: certbot-storage
          persistentVolumeClaim:
            claimName: certificates-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: certbot
  labels:
    app: certbot
spec:
  ports:
    - port: 80
      protocol: TCP
  type: LoadBalancer
  loadBalancerIP: 192.168.2.224
  selector:
    app: certbot
---
# EFF recommends running `certbot renew` a couple times per day.
# Kubernetes doesn't make this kind of pattern very easy.
# An externally accessible endpoint is needed, and it needs access to the
#   certificates volume.
# Run `certbot renew` in an already running certbot pod occasionally.
# This may or may not work depending on how the persistent volume claim works.
# Jobs run successfully, but once renewal time comes up, they may fail.
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: certbot-renew
spec:
  schedule: "32 4,16 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: certbot
              image: certbot/certbot
              args:
                - renew
              volumeMounts:
              - name: certbot-storage
                mountPath: /etc/letsencrypt
          volumes:
            - name: certbot-storage
              persistentVolumeClaim:
                claimName: certificates-pv-claim
          restartPolicy: OnFailure
