apiVersion: v1
kind: PersistentVolume
metadata:
  name: sharelatex-pv
  labels:
    identifier: sharelatex
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=3
  nfs:
    path: /kubernetes-test/sharelatex
    server: 192.168.1.42
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sharelatex-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      identifier: sharelatex
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sharelatex-deployment
  labels:
    app: sharelatex
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: sharelatex
  template:
    metadata:
      labels:
        app: sharelatex
    spec:
      containers:
        - name: sharelatex
          image: sharelatex/sharelatex
          ports:
            - containerPort: 80
          env:
            - name: SHARELATEX_REDIS_HOST
              value: redis
            - name: SHARELATEX_MONGO_URL
              value: mongodb://mongodb:27017/sharelatex
          volumeMounts:
            - name: sharelatex-persistent-storage
              mountPath: /var/lib/sharelatex
      volumes:
        - name: sharelatex-persistent-storage
          persistentVolumeClaim:
            claimName: sharelatex-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: sharelatex
  labels:
    app: sharelatex
spec:
  ports:
    - port: 80
      protocol: TCP
  type: LoadBalancer
  loadBalancerIP:
  selector:
    app: sharelatex
