apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-block-storage
  labels:
    identifier: plex
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  iscsi:
    targetPortal: 192.168.96.4
    iqn: iqn.2019-05.com.aleemhaji.internal.ctl:plex
    lun: 14
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  selector:
    matchLabels:
      identifier: plex
