# This is a template CronJob definition that can be used to create an entity
#   in Kubernetes that will rsync one directory to another.
# It creates a job that runs one rsync comment between two volumes of choice.
# Currently only supports NFS shares
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ${CRONJOB_NAME}-backup
spec:
  schedule: "0 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          imagePullSecrets: 
            - name: registry.internal.aleemhaji.com
          containers:
            - name: rsync
              image: registry.internal.aleemhaji.com/rsync:latest
              command:
                - sh
                - -c
                - rsync ${RSYNC_OPTIONS} /data/source${SOURCE_PATH} /data/dest${DEST_PATH}
              volumeMounts:
                - name: ${CRONJOB_NAME}-source
                  mountPath: /data/source
                - name: ${CRONJOB_NAME}-destination
                  mountPath: /data/dest
          volumes:
            - name: ${CRONJOB_NAME}-source
              nfs:
                server: ${SOURCE_NFS_SERVER}
                path: ${SOURCE_NFS_DIRECTORY}
            - name: ${CRONJOB_NAME}-destination
              nfs:
                server: ${DESTINATION_NFS_SERVER}
                path: ${DESTINATION_NFS_DIRECTORY}
