apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea-deployment
  labels:
    app: gitea
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
    spec:
      containers:
        - name: gitea
          image: gitea/gitea:1.9.0
          ports:
            - containerPort: 3000
            - containerPort: 22
          volumeMounts:
            - name: gitea-persistent-storage
              mountPath: /data
            - name: ssl-cert
              mountPath: /etc/ssl/certs/
      volumes:
        - name: gitea-persistent-storage
          nfs:
            server: 192.168.1.42
            path: /kubernetes-test/gitea
        - name: ssl-cert
          projected:
            sources:
              - secret:
                  name: internal-certificate-files
---
apiVersion: v1
kind: Service
metadata:
  name: gitea
  labels:
    app: gitea
spec:
  ports:
    - port: 443
      protocol: TCP
      name: web
      targetPort: 3000
    - port: 22
      protocol: TCP
      name: ssh
  type: LoadBalancer
  loadBalancerIP:
  selector:
    app: gitea
