apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: monitoring
  name: grafana-ingress-redirect
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/temporal-redirect: https://grafana.internal.aleemhaji.com
spec:
  rules:
    - host: grafana
    - host: grafana.home
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: monitoring
  name: grafana-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
        - grafana.internal.aleemhaji.com
      secretName: internal-certificate-files
  rules:
    - host: grafana.internal.aleemhaji.com
      http:
        paths:
          - path: /
            backend:
              serviceName: grafana
              servicePort: 3000
