apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: trilium-deployment
  labels:
    app: trilium
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: trilium
  template:
    metadata:
      labels:
        app: trilium
    spec:
      imagePullSecrets: 
        - name: registry.internal.aleemhaji.com
      containers:
        - name: trilium
          image: registry.internal.aleemhaji.com/trilium:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: trilium-persistent-storage
              mountPath: /var/lib/trilium
      volumes:
        - name: trilium-persistent-storage
          nfs:
            server: 192.168.1.42
            path: /kubernetes-test/trilium
---
apiVersion: v1
kind: Service
metadata:
  name: trilium
  labels:
    app: trilium
spec:
  ports:
    - port: 8080
      protocol: TCP
  type: LoadBalancer
  loadBalancerIP:
  selector:
    app: trilium
