apiVersion: v1
kind: PersistentVolume
metadata:
  name: trilium-pv
  labels:
    identifier: trilium
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=3
  nfs:
    path: /kubernetes-test/trilium
    server: 192.168.1.42
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trilium-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      identifier: trilium
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trilium-deployment
  labels:
    app: trilium
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: trilium
  template:
    metadata:
      labels:
        app: trilium
    spec:
      imagePullSecrets: 
        - name: registry.internal.aleemhaji.com
      containers:
        - name: trilium
          image: registry.internal.aleemhaji.com/trilium:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: trilium-persistent-storage
              mountPath: /var/lib/trilium
      volumes:
        - name: trilium-persistent-storage
          persistentVolumeClaim:
            claimName: trilium-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: trilium
  labels:
    app: trilium
spec:
  ports:
    - port: 8080
      protocol: TCP
  type: LoadBalancer
  loadBalancerIP:
  selector:
    app: trilium
