apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  labels:
    identifier: mongodb
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=3
  nfs:
    path: /kubernetes-test/mongodb
    server: 192.168.1.42
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  serviceName: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      terminationGracePeriodSeconds: 120
      containers:
        - name: mongodb
          image: mongo:3.7
          args:
            - --sslMode
            - preferSSL
            - --sslPEMKeyFile
            - /etc/ssl/mongodb.pem
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-persistent-storage
              mountPath: /data/db
            - name: mongodb-pem
              mountPath: /etc/ssl/mongodb.pem
              subPath: keycert.pem
      volumes:
        - name: mongodb-pem
          projected:
            sources:
              - secret:
                  name: internal-certificate-file
  volumeClaimTemplates:
    - metadata:
        name: mongodb-persistent-storage
      spec:
        accessModes: 
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        selector:
          matchLabels:
            identifier: mongodb
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  ports:
  - port: 27017
    protocol: TCP
  type: LoadBalancer
  loadBalancerIP:
  selector:
    app: mongodb
