apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-repair-pv
  labels:
    identifier: mongodb-repair
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=3
  nfs:
    path: /kubernetes-test/mongodb
    server: 192.168.1.42
---
apiVersion: v1  
kind: PersistentVolumeClaim 
metadata: 
  name: mongodb-repair-pv-claim  
spec: 
  accessModes:  
    - ReadWriteOnce 
  resources:  
    requests: 
      storage: 5Gi  
  selector: 
    matchLabels:  
      identifier: mongodb-repair
---
apiVersion: batch/v1
kind: Job
metadata:
  name: mongodb-repair-job
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: mongodb-repair
          image: mongo:3.7
          command:
            - mongod
            - --repair
          env:
          volumeMounts:
            - name: mongodb-storage
              mountPath: /data/db
      volumes:
        - name: mongodb-storage
          persistentVolumeClaim:
            claimName: mongodb-repair-pv-claim
