apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-backups-pv
  labels:
    identifier: mongodb-backups
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=3
  nfs:
    path: /kubernetes-test/backups/mongodb
    server: 192.168.1.42
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-backups-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      identifier: mongodb-backups
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: mongodb-backup
spec:
  schedule: "0 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: mongo
              image: mongo:3.7
              command:
                - mongodump
                - -h
                - mongo.internal.aleemhaji.com
                - -o
                - /var/lib/backups
              volumeMounts:
              - name: backups
                mountPath: /var/lib/backups
          volumes:
            - name: backups
              persistentVolumeClaim:
                claimName: mongodb-backups-pv-claim
