# MongoDB set up with an WiredTiger cache size.
# Without the explicit cap, MongoDB will just eat up memory without fear,
#   and get itself OOM killed.
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  serviceName: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      terminationGracePeriodSeconds: 120
      containers:
        - name: mongodb
          image: mongo:3.7
          args:
            - --sslMode
            - preferSSL
            - --sslPEMKeyFile
            - /etc/ssl/mongodb.pem
            - --wiredTigerCacheSizeGB
            - "1"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-persistent-storage
              mountPath: /data/db
            - name: mongodb-pem
              mountPath: /etc/ssl/mongodb.pem
              subPath: keycert.pem
      volumes:
        - name: mongodb-persistent-storage
          nfs:
            server: 192.168.1.42
            path: /kubernetes-test/mongodb
        - name: mongodb-pem
          projected:
            sources:
              - secret:
                  name: internal-certificate-file
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  ports:
  - port: 27017
    protocol: TCP
  type: LoadBalancer
  loadBalancerIP:
  selector:
    app: mongodb
