apiVersion: batch/v1
kind: Job
metadata:
  name: mongodb-restore-job-${RESTORE_MONGODB_DATABASE}
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: mongodb-restore
          image: mongo:3.7
          command:
            - sh
            - -c
            - mongorestore --host ${MONGODB_HOST} --drop --db ${RESTORE_MONGODB_DATABASE} /restore/${RESTORE_MONGODB_DATABASE}
          env:
            - name: MONGODB_HOST
              valueFrom:
                configMapKeyRef:
                  name: network-ip-assignments
                  key: mongodb
          volumeMounts:
            - name: mongodb-restore-storage
              mountPath: /restore
      volumes:
        - name: mongodb-restore-storage
          nfs:
            server: 192.168.1.42
            path: /kubernetes-test/mongodb-restore
