apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: mongodb-trim
spec:
  schedule: "0 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: mongodb-trim
              image: mongo:3.7
              command:
                - sh
                - -e
                - -x
                - -c
                - |
                  last_month=$(date -u +%Y-%m-%dT%H:%M:%SZ -d "1 month ago")
                  mongo $MONGODB_HOST/blobstore --eval 'db.logs.remove({time:{$lt:ISODate("'$last_month'")}})'
                  mongo $MONGODB_HOST/remind-me-bot --eval 'db.logs.remove({time:{$lt:ISODate("'$last_month'")}})'
              env:
                - name: MONGODB_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: network-ip-assignments
                      key: mongodb
