apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.15.12
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: nginx-servers
              mountPath: /etc/nginx/conf.d/
            - name: nginx-certs
              mountPath: /etc/ssl/certs/
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
        - name: nginx-servers
          configMap:
            name: nginx-servers
        - name: nginx-certs
          projected:
            sources:
              - secret:
                  name: certificate-files
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
    - port: 80
      protocol: TCP
      name: nginx-http-port
    - port: 443
      protocol: TCP
      name: nginx-https-port
  type: LoadBalancer
  loadBalancerIP:
  selector:
    app: nginx
