apiVersion: v1
kind: PersistentVolume
metadata:
  name: factorio-pv
  labels:
    identifier: factorio
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=3
  nfs:
    path: /kubernetes-test/factorio
    server: 192.168.1.42
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: factorio-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      identifier: factorio
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: factorio-deployment
  labels:
    app: factorio
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: factorio
  template:
    metadata:
      labels:
        app: factorio
    spec:
      imagePullSecrets: 
        - name: registry.internal.aleemhaji.com
      containers:
        - name: factorio
          image: registry.internal.aleemhaji.com/factorio:latest
          ports:
            - containerPort: 34197
          volumeMounts:
            - name: factorio-persistent-storage
              mountPath: /var/lib/factorio/saves
          env:
            - name: SAVE_GAME
              value: abc
      volumes:
        - name: factorio-persistent-storage
          persistentVolumeClaim:
            claimName: factorio-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: factorio
  labels:
    app: factorio
spec:
  ports:
    - port: 34197
      protocol: UDP
  type: LoadBalancer
  loadBalancerIP:
  selector:
    app: factorio
