apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-restore-pv
  labels:
    identifier: mysql-restore
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=3
  nfs:
    path: /kubernetes-test/mysql-restore
    server: 192.168.1.42
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-restore-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      identifier: mysql-restore
---
apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-restore-job-${JOB_CREATION_TIMESTAMP}
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: mysql-restore
          image: mysql:5.7.26
          command:
            - sh
            - -c
            - find restore -iname *.sql -print | while read filename; do mysql -h ${MYSQL_HOST} -u root --database=${RESTORE_MYSQL_DATABASE} < $filename; done
          env:
            - name: MYSQL_PWD
              valueFrom:
                secretKeyRef:
                  name: mysql-root-password
                  key: value
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: network-ip-assignments
                  key: mysql
          volumeMounts:
            - name: mysql-restore-storage
              mountPath: /restore
      volumes:
        - name: mysql-restore-storage
          persistentVolumeClaim:
            claimName: mysql-restore-pv-claim
