apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-0
  labels:
    identifier: mysql
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=3
  nfs:
    path: /kubernetes-test/mysql
    server: 192.168.1.42
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-1
  labels:
    identifier: mysql
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=3
  nfs:
    path: /kubernetes-test/mysql
    server: 192.168.1.42
