apiVersion: v1
kind: PersistentVolume
metadata:
  name: tedbot-pv
  labels:
    identifier: tedbot
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=3
  nfs:
    path: /kubernetes-test/tedbot
    server: 192.168.1.42
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tedbot-pv-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      identifier: tedbot
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: tedbot
spec:
  schedule: "0 12 * * 1-5"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: tedbot
        spec:
          restartPolicy: OnFailure
          imagePullSecrets:
            - name: registry.internal.aleemhaji.com
          containers:
            - name: tedbot
              image: registry.internal.aleemhaji.com/tedbot:latest
              volumeMounts:
                - name: tedbot-storage
                  mountPath: /app/artifacts
              env:
                - name: HOOK_URL 
                  valueFrom:
                    secretKeyRef:
                      name: tedbot-webhook-url
                      key: value
          volumes:
            - name: tedbot-storage
              persistentVolumeClaim:
                claimName: tedbot-pv-claim
