apiVersion: v1
kind: PersistentVolume
metadata:
  name: downloads-pv
  labels:
    identifier: downloads
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=3
  nfs:
    path: /kubernetes-test/downloads
    server: 192.168.1.42
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  selector:
    matchLabels:
      identifier: downloads
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: transmission-pv
  labels:
    identifier: transmission
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=3
  nfs:
    path: /kubernetes-test/transmission
    server: 192.168.1.42
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      identifier: transmission
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: transmission-deployment
  labels:
    app: transmission
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: transmission
  template:
    metadata:
      labels:
        app: transmission
    spec:
      imagePullSecrets:
        - name: registry.internal.aleemhaji.com
      containers:
        - name: transmission
          image: registry.internal.aleemhaji.com/transmission:latest
          ports:
            - containerPort: 9091
          volumeMounts:
            - name: downloads-persistent-storage
              mountPath: /var/lib/downloads
            - name: transmission-persistent-storage
              mountPath: /var/lib/transmission-daemon
      volumes:
        - name: downloads-persistent-storage
          persistentVolumeClaim:
            claimName: downloads-pv-claim
        - name: transmission-persistent-storage
          persistentVolumeClaim:
            claimName: transmission-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: transmission
  labels:
    app: transmission
spec:
  ports:
    - port: 9091
      protocol: TCP
  type: LoadBalancer
  loadBalancerIP:
  selector:
    app: transmission
