apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: transmission-deployment
  labels:
    app: transmission
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: transmission
  template:
    metadata:
      labels:
        app: transmission
    spec:
      imagePullSecrets:
        - name: registry.internal.aleemhaji.com
      containers:
        - name: transmission
          image: registry.internal.aleemhaji.com/transmission:latest
          ports:
            - containerPort: 9091
          volumeMounts:
            - name: downloads-persistent-storage
              mountPath: /var/lib/downloads
            - name: transmission-persistent-storage
              mountPath: /var/lib/transmission-daemon
      volumes:
        - name: downloads-persistent-storage
          nfs:
            server: 192.168.1.42
            path: /kubernetes-test/downloads
        - name: transmission-persistent-storage
          nfs:
            server: 192.168.1.42
            path: /kubernetes-test/transmission
---
apiVersion: v1
kind: Service
metadata:
  name: transmission
  labels:
    app: transmission
spec:
  ports:
    - port: 9091
      protocol: TCP
  type: LoadBalancer
  loadBalancerIP:
  selector:
    app: transmission
