apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission-deployment
  labels:
    app: transmission
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: transmission
  template:
    metadata:
      labels:
        app: transmission
    spec:
      imagePullSecrets:
        - name: registry.internal.aleemhaji.com
      containers:
        - name: transmission
          image: registry.internal.aleemhaji.com/transmission:latest
          ports:
            - containerPort: 9091
          volumeMounts:
            - name: downloads-persistent-storage
              mountPath: /var/lib/downloads
            - name: transmission-persistent-storage
              mountPath: /var/lib/transmission-daemon
      volumes:
        - name: downloads-persistent-storage
          nfs:
            server: 192.168.1.42
            path: /kubernetes-test/downloads
        - name: transmission-persistent-storage
          nfs:
            server: 192.168.1.42
            path: /kubernetes-test/transmission
---
apiVersion: v1
kind: Service
metadata:
  name: transmission
  labels:
    app: transmission
spec:
  ports:
    - port: 9091
      protocol: TCP
  type: LoadBalancer
  loadBalancerIP:
  selector:
    app: transmission
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: transmission-ingress-redirect
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/temporal-redirect: https://transmission.internal.aleemhaji.com
spec:
  rules:
    - host: transmission
    - host: transmission.home
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: transmission-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  tls:
    - hosts:
        - transmission.internal.aleemhaji.com
      secretName: internal-certificate-files
  rules:
    - host: transmission.internal.aleemhaji.com
      http:
        paths:
          - path: /
            backend:
              serviceName: transmission
              servicePort: 9091
